spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: warn
    com.steve: info
  file: log/blog-pro.log
server:
  port: 8081
